### ISSUE TITLE
Getting an error: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by gajus** [myndzi/wtfnode#2]
Having `require('wtfnode').dump();` triggers the following error:

```
TypeError: Cannot read property 'file' of undefined
    at ./node_modules/wtfnode/index.js:108:107
    at Array.forEach (native)
    at ./node_modules/wtfnode/index.js:107:34
    at Array.forEach (native)
    at Object.dump (./node_modules/wtfnode/index.js:98:17)
    at PoolConnection.<anonymous> (createPool.js:12:36)
    at FunctionDisposer.doDispose (./node_modules/bluebird/js/release/using.js:97:19)
    at FunctionDisposer.Disposer.tryDispose (./node_modules/bluebird/js/release/using.js:77:20)
    at iterator (./node_modules/bluebird/js/release/using.js:35:53)
    at dispose (./node_modules/bluebird/js/release/using.js:47:9)
    at ./node_modules/bluebird/js/release/using.js:193:20
    at PassThroughHandlerContext.finallyHandler (./node_modules/bluebird/js/release/finally.js:55:23)
    at PassThroughHandlerContext.tryCatcher (./node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (./node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (./node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (./node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (./node_modules/bluebird/js/release/promise.js:684:18)
    at Promise._fulfill (./node_modules/bluebird/js/release/promise.js:629:18)
    at Promise._resolveCallback (./node_modules/bluebird/js/release/promise.js:446:14)
    at Promise._settlePromiseFromHandler (./node_modules/bluebird/js/release/promise.js:515:17)
    at Promise._settlePromise (./node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (./node_modules/bluebird/js/release/promise.js:605:10)
```

Context:

```js
import mysql from './mysql';

export default (connectionOptions) => {
    const pool = mysql.createPool(connectionOptions);

    const getConnection = () => {
        return pool
            .getConnectionAsync()
            .disposer((connection) => {
                connection.release();

                require('wtfnode').dump();
            });
    };

    return {
        end: () => {
            return pool.endAsync();
        },
        getConnection
    };
};

```

Note that the code is executed using `babel-node` with "react", "es2015" and "stage-0" presets.

**Comment by gajus** [comment]
Node v0.15.10.

**Comment by myndzi** [comment]
Thanks for the report. `wtfnode` very much depends upon a bunch of easily breakable assumptions, including private APIs, so this sort of thing is unfortunately par for the course. I do suggest maybe putting the `.dump` call in an isolated event loop if possible, which is to say delay it with a setImmediate or setTimeout so that any handles that are extant during this portion of your code have the opportunity to be removed from Node's list. That might get you by in the meanwhile if lucky!

**Comment by myndzi** [comment]
This wasn't nearly a complete test case, but it got me there. I inferred you're using Bluebird's disposer API from the code.

This one actually isn't a bug. You require `wtfnode` late in your code, so it's unable to hook the node internals it needs in order to be able to display to you the call site of the listeners. Put `require('wtfnode')` at the top of your code's entry point and it will not throw. I'll see about putting a friendlier error message.
