### ISSUE TITLE
stream.on(...) returns undefined instead of this with wtfnode@0.7.2

### ISSUE THREAD

**Issue by aucampia** [myndzi/wtfnode#31]
`index.js`:

```js
const wtfnode = require("wtfnode")
const fs = require("fs")

fs.createWriteStream("/var/tmp/whynowork.log", {})
	.on('error', err => console.log(err))
	.on('close', () => console.log('close'));

console.log(`done`);
```

with 0.7.1

```
$ npm list
wtfnode-bug-000@1.0.0 /var/tmp/wtfnode-bug-000
└── wtfnode@0.7.1
$ node index.js 
done
```

with 0.7.2

```
$ npm list
wtfnode-bug-000@1.0.0 /var/tmp/wtfnode-bug-000
└── wtfnode@0.7.2

$ node index.js 
/var/tmp/wtfnode-bug-000/index.js:6
	.on('close', () => console.log('close'));
	^

TypeError: Cannot read property 'on' of undefined
    at Object.<anonymous> (/var/tmp/wtfnode-bug-000/index.js:6:2)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by myndzi** [comment]
Should be fixed, can you verify? I published straight to latest since it was broken anyway.

**Comment by aucampia** [comment]
`0.7.3` seems fine, thanks for prompt response and correction.

**Comment by myndzi** [comment]
Great! :)
