### ISSUE TITLE
wtfnode crashes

### ISSUE THREAD

**Issue by TimDaub** [myndzi/wtfnode#37]
```bash
$ wtfnode src/server.js
/usr/local/lib/node_modules/wtfnode/index.js:284
        var before = emitter.listeners(type);
TypeError: emitter.listeners is not a function
    at addListener (/usr/local/lib/node_modules/wtfnode/index.js:284:30)
    at EventEmitter.Cls.(anonymous function) [as on] (/usr/local/lib/node_modules/wtfnode/index.js:307:27)
    at Object.<anonymous> (/home/pi/http-sms-gateway/src/controllers/tasks.js:39:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
```

Can't tell if it's a problem with my code or wtfnode. I'm using express.js if that's interesting...

**Comment by myndzi** [comment]
What version of node?

**Comment by myndzi** [comment]
The only thing I can think of that might be to do with your code is if you have an event emitter that you set the `listeners` property to some data on. I know how to code around that, but you probably don't want to do that anyway. Do you do anything like that?

**Comment by TimDaub** [comment]
Hey sorry for taking so long to respond:

```bash
$ node --version
v13.9.0
```

> The only thing I can think of that might be to do with your code is if you have an event emitter that you set the listeners property to some data on.

Not exactly sure what you mean. Can you make an example how that would look like? I'm using events but I'm not aware of doing what you're suggesting...

**Comment by myndzi** [comment]
`listeners` is a function provided by the EventEmitter class. If you make an event emitter, and assign something to that property, it would cause this error if you tried to subsequently bind an event.

Example:


```
$ cat issue-37.js
const EventEmitter = require('events').EventEmitter;

const ee = new EventEmitter();
ee.listeners = [];
ee.on('foo', () => {});

$ node --version
v13.9.0

$ cat issue-37.js
const EventEmitter = require('events').EventEmitter;

const ee = new EventEmitter();
ee.listeners = [];
ee.on('foo', () => {});

$ node issue-37.js

$ wtfnode issue-37.js
/home/myndzi/wtfnode/index.js:284
        var before = emitter.listeners(type);
                             ^

TypeError: emitter.listeners is not a function
    at addListener (/home/myndzi/wtfnode/index.js:284:30)
    at EventEmitter.Cls.<computed> [as on] (/home/myndzi/wtfnode/index.js:307:27                        )
    at Object.<anonymous> (/home/myndzi/wtfnode/issue-37.js:5:4)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js                        :71:12)
    at Object.<anonymous> (/home/myndzi/wtfnode/index.js:714:12)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
```

**Comment by myndzi** [comment]
I've published a version that makes wtfnode robust against this problem, but you should note that this is a problem in either your application code or a library that you're using. It's not a good idea to overwrite Node API methods with incompatible values; other things may fail in this same way

**Comment by TimDaub** [comment]
I tried again and it works now. Thanks 👍

**Comment by myndzi** [comment]
Be sure to fix your code :)
