### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by ig3** [myndzi/wtfnode#50]
I encountered an error when running wtf.dump():

```
[WTF Node?] open handles:
- File descriptors: (note: stdio always exists)
  - fd 2 (tty) (stdio)
  - fd 1 (tty) (stdio)
- Sockets:
  - 127.0.0.1:39668 -> 127.0.0.1:39651
    - GET http://127.0.0.1:39651/testdb/_changes?feed=continuous&heartbeat=30000
  - 127.0.0.1:39651 -> 127.0.0.1:39668
/home/ian/dev/@ig3/couchdb/node_modules/wtfnode/index.js:567
                var host = req.host || req.getHeader('host').replace(/:\d+$/, '');
                                                            ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at /home/ian/dev/@ig3/couchdb/node_modules/wtfnode/index.js:567:61
    at Array.forEach (<anonymous>)
    at Object.dump (/home/ian/dev/@ig3/couchdb/node_modules/wtfnode/index.js:553:17)
```

**Comment by myndzi** [comment]
Should be fixed now
